language: android
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-25
    - sys-img-armeabi-v7a-android-22
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
